name: $(Build.BuildId)
trigger:
  # This is where pull requests from "bors r+" are built.
  - staging
  # This is where pull requests from "bors try" are built.
  - trying
  # Always build master
  - master
pr:
  # Enable building pull requests.
  - master
stages:
  - stage: Testing
    jobs:
      - job:
        variables:
          rust: 1.40.0
        strategy:
          matrix:
            MSVC 32-bit:
              image: vs2017-win2016
              target: i686-pc-windows-msvc
            MSVC 64-bit:
              image: vs2017-win2016
              target: x86_64-pc-windows-msvc
            MinGW 32-bit:
              image: vs2017-win2016
              target: i686-pc-windows-gnu
            MinGW 64-bit:
              image: vs2017-win2016
              target: x86_64-pc-windows-gnu
        pool:
          vmImage: $(image)
        steps:
          - checkout: self
            fetchDepth: 1
            path: clap
            displayName: Checkout repository
          - task: Cache@2
            inputs:
              key: cargo | "$(rust)" | $(target) | Cargo.toml
              path: C:\Rust\.cargo
            displayName: Cache cargo
          - script: rustup default $(rust)-$(target)
            displayName: Install rust
          - script: cargo test --features "yaml unstable"
            displayName: Test with most features
          - script: |
              rmdir /Q /S C:\Rust\.cargo\registry\src
            displayName: Cleanup cache
            continueOnError: true
